# 全局配置
global:
  scrape_interval: 15s       # 采集指标的时间间隔，默认15秒; 用于Prometheus从目标采集指标
  evaluation_interval: 15s   # 规则评估的时间间隔，默认15秒; 用于Prometheus评估告警规则

# 告警配置
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9050']

# 告警规则文件路径
rule_files:
  - '/etc/prometheus/rules.yml'

# 采集配置
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'go-app'
    static_configs:
      - targets: ['192.168.140.128:8015']